
services:
  fuseki:
    image: stain/jena-fuseki:latest
    ports:
      - "13030:3030"
    networks:
      - knowledgebase-processor
    environment:
      - ADMIN_PASSWORD=admin
      - JVM_ARGS=-Xmx2g
    volumes:
      - ./fuseki-data:/fuseki
      - ./fuseki-staging:/staging
    user: "1000:1000"
    command: ["/jena-fuseki/fuseki-server", "--update", "--mem", "/test"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3030/$/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  fuseki-data:


networks:
  knowledgebase-processor:
    external: true

