name: Build Artifacts

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build Docker image
      run: |
        docker build -t knowledgebase-processor:latest .
        docker save knowledgebase-processor:latest | gzip > knowledgebase-processor-docker.tar.gz
    
    - name: Upload Docker artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-image
        path: knowledgebase-processor-docker.tar.gz

  build-wheel:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install Poetry
      uses: snok/install-poetry@v1
    
    - name: Build wheel
      run: |
        poetry build
    
    - name: Upload wheel
      uses: actions/upload-artifact@v4
      with:
        name: python-wheel
        path: dist/

  # build-executable:
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     matrix:
  #       os: [ubuntu-latest, windows-latest, macos-latest]
    
  #   steps:
  #   - uses: actions/checkout@v4
    
  #   - name: Set up Python
  #     uses: actions/setup-python@v4
  #     with:
  #       python-version: '3.12'
    
  #   - name: Install Poetry
  #     uses: snok/install-poetry@v1
    
  #   - name: Install dependencies
  #     run: |
  #       poetry install --only=main
    
  #   - name: Install PyInstaller
  #     run: |
  #       poetry add --group dev pyinstaller
    
  #   - name: Build executable
  #     run: |
  #       poetry run pyinstaller --onefile --name kb src/knowledgebase_processor/cli_v2/main.py
    
  #   - name: Upload executable
  #     uses: actions/upload-artifact@v4
  #     with:
  #       name: executable-${{ matrix.os }}
  #       path: dist/kb*